Feature/gestione autonoma pianificazione attivita
istricesrl/glisweb pull request #296
Opened 2021-05-21 13:21 UTC by silvia-df

Le attività ora hanno il settaggio di data e orari programmazione
- nella form.html inserito il preset (solo table) per le macro date e time
- impostato il preset di data e orario di programmazione di un'attività figlia di una todo
- aggiornato il workspace di pianificazione todo per settare anche data_programmazione_attivita

Modifiche per velocizzare il calcolo dei sostituti
- modificato le funzioni di calcolo sostituti progetto e attività in modo da leggere i dati dalla tabella attivita invece che dalla vista
- modificato il task sostituzioni.calculate.php con utilizzo del timestamp

Eliminazione progetto
- modificato il task di eliminazione di un progetto in modo che rimuova prima le todo e attività figlie, poi il progetto stesso

2021-05-21 14:23 UTC, fabiomosti requested changes

2021-05-21 14:23 UTC, fabiomosti commented on _mod/_1000.produzione/_src/_api/_task/_progetti.delete.php
> +
qui puoi direttamente usare mysqlDeleteRowRecursive()

2021-05-24 17:11 UTC, silvia-df commented on _mod/_1000.produzione/_src/_api/_task/_progetti.delete.php
> +
sì ho fatto, grazie!

2021-05-25 11:31 UTC, fabiomosti approved these changes

2021-05-25 11:31 UTC, merged